name: chat_gui
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter 

  get: ^4.7.2
  get_storage: ^2.1.1
  lucide_icons_flutter: ^3.0.9
  intl: ^0.20.2 
  gpt_markdown: ^1.1.3
  flutter_highlight: ^0.7.0
  highlight: ^0.7.0
  url_launcher: ^6.3.2
  extended_image: ^10.0.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: MapleMono
      fonts:
        - asset: assets/fonts/MapleMonoNL-Regular.ttf
        
  assets:
    - assets/lang/
